const destinationsData = [
  {
    _id: '68c25fa70c3c015c668891e2',
    title: 'Kashmir',
    description: 'Known as Paradise on Earth, with breathtaking landscapes and vibrant culture.',
    imgSrc: '/images/kashmir.jpg',
    location: 'Jammu & Kashmir',
    bestTimeToVisit: 'April to October',
    activities: ['Boating', 'Skiing', 'Photography'],
    tips: 'Carry warm clothes even in summers.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹5000/day', high: '₹10000/day' },
    itinerary: ['Day 1: Srinagar sightseeing', 'Day 2: Gulmarg skiing', 'Day 3: Pahalgam trek']
  },
  {
    _id: '68c25fa70c3c015c668891e3',
    title: 'Varanasi',
    description: 'A spiritual city on the banks of the Ganges River, famous for rituals and temples.',
    imgSrc: '/images/varanasi.jpg',
    location: 'Uttar Pradesh',
    bestTimeToVisit: 'October to March',
    activities: ['Ganga Aarti', 'Temple Visits', 'Boat Ride'],
    tips: 'Respect local customs and traditions.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹4000/day', high: '₹8000/day' },
    itinerary: ['Day 1: Boat ride & Aarti', 'Day 2: Kashi Vishwanath & markets', 'Day 3: Sarnath trip']
  },
  {
    _id: '68c25fa70c3c015c668891e4',
    title: 'Manali',
    description: 'A beautiful hill station with scenic valleys and adventure activities.',
    imgSrc: '/images/manali.jpg',
    location: 'Himachal Pradesh',
    bestTimeToVisit: 'March to June',
    activities: ['Trekking', 'Skiing', 'Paragliding'],
    tips: 'Book hotels in advance during peak season.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹5000/day', high: '₹10000/day' },
    itinerary: ['Day 1: Solang Valley', 'Day 2: Rohtang Pass', 'Day 3: Old Manali']
  },
  {
    _id: '68c25fa70c3c015c668891e5',
    title: 'Vrindavan',
    description: 'A holy city associated with Lord Krishna, with colorful temples.',
    imgSrc: '/images/mero_vrindavan.jpg',
    location: 'Uttar Pradesh',
    bestTimeToVisit: 'October to March',
    activities: ['Temple Visits', 'Cultural Walks', 'Festivals'],
    tips: 'Visit during festivals for vibrant experience.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1000/day', medium: '₹3000/day', high: '₹6000/day' },
    itinerary: ['Day 1: Banke Bihari temple', 'Day 2: ISKCON temple & local markets', 'Day 3: Cultural walk']
  },
  {
    _id: '68c27177030b9fcba7e7159c',
    title: 'Jaipur',
    description: 'The Pink City, rich in history and culture with palaces and forts.',
    imgSrc: '/images/jaipur.jpg',
    location: 'Rajasthan',
    bestTimeToVisit: 'October to March',
    activities: ['Palace Tours', 'Shopping', 'Elephant Rides'],
    tips: 'Hire a guide for historical insights.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: City Palace & Jantar Mantar', 'Day 2: Amber Fort & elephant ride', 'Day 3: Local bazaars']
  },
  {
    _id: '68c271f7030b9fcba7e7159f',
    title: 'Goa',
    description: 'Famous for beaches, nightlife, and Portuguese heritage.',
    imgSrc: '/images/goa.jpg',
    location: 'Goa',
    bestTimeToVisit: 'November to February',
    activities: ['Beach Hopping', 'Water Sports', 'Night Markets'],
    tips: 'Rent a scooter to explore the coast.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹5000/day', high: '₹12000/day' },
    itinerary: ['Day 1: North Goa beaches', 'Day 2: South Goa relax & culture', 'Day 3: Water sports & night market']
  },
  {
    _id: '68c2724a030b9fcba7e715a1',
    title: 'Rishikesh',
    description: 'Yoga capital of the world and adventure hub by the Ganges.',
    imgSrc: '/images/rishikesh.jpg',
    location: 'Uttarakhand',
    bestTimeToVisit: 'September to November',
    activities: ['River Rafting', 'Yoga Retreats', 'Camping'],
    tips: 'Morning Ganga Aarti is a must-see.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1200/day', medium: '₹3500/day', high: '₹8000/day' },
    itinerary: ['Day 1: Rafting & Laxman Jhula', 'Day 2: Yoga retreat', 'Day 3: Trek & meditation']
  },
  {
    _id: '68c27267030b9fcba7e715a3',
    title: 'Udaipur',
    description: 'City of Lakes, known for palaces, lakes, and serene beauty.',
    imgSrc: '/images/udaipur.jpg',
    location: 'Rajasthan',
    bestTimeToVisit: 'September to March',
    activities: ['Lake Pichola Boating', 'Palace Visit', 'Photography'],
    tips: 'Evening boat rides are magical.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1800/day', medium: '₹4500/day', high: '₹10000/day' },
    itinerary: ['Day 1: City Palace & Lake Pichola', 'Day 2: Jag Mandir & gardens', 'Day 3: Local markets & temples']
  },
  {
    _id: '68c2727c030b9fcba7e715a5',
    title: 'Mysore',
    description: 'City of Palaces and rich cultural heritage.',
    imgSrc: '/images/mysore.jpg',
    location: 'Karnataka',
    bestTimeToVisit: 'October to March',
    activities: ['Palace Tour', 'Zoo Visit', 'Local Markets'],
    tips: 'Visit during Dasara festival for grand celebrations.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: Mysore Palace', 'Day 2: Zoo & local markets', 'Day 3: Chamundi Hill']
  },
  {
    _id: '68c272b1030b9fcba7e715a7',
    title: 'Darjeeling',
    description: 'Famous for tea gardens and scenic views.',
    imgSrc: '/images/darjeeling.jpg',
    location: 'West Bengal',
    bestTimeToVisit: 'March to May, October to December',
    activities: ['Tea Garden Tour', 'Toy Train', 'Hiking'],
    tips: 'Try local tea and momos.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹4500/day', high: '₹10000/day' },
    itinerary: ['Day 1: Tiger Hill & sunrise', 'Day 2: Tea garden & Darjeeling town', 'Day 3: Trekking nearby']
  },
  {
    _id: '68c272cc030b9fcba7e715a9',
    title: 'Andaman Islands',
    description: 'Tropical paradise with pristine beaches, coral reefs, and clear waters.',
    imgSrc: '/images/AndamanIslands.jpg',
    location: 'Andaman & Nicobar Islands',
    bestTimeToVisit: 'October to May',
    activities: ['Scuba Diving', 'Snorkeling', 'Beach Hopping', 'Water Sports'],
    tips: 'Book ferry tickets in advance.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹3000/day', medium: '₹7000/day', high: '₹15000/day' },
    itinerary: ['Day 1: Havelock Island', 'Day 2: Radhanagar Beach', 'Day 3: Scuba & snorkeling']
  },
  {
    _id: '68c272e3030b9fcba7e715ab',
    title: 'Hampi',
    description: 'Ruins of Vijayanagara Empire with unique boulder landscapes.',
    imgSrc: '/images/hampi.jpg',
    location: 'Karnataka',
    bestTimeToVisit: 'October to March',
    activities: ['Temple Tours', 'Boulder Climbing', 'Photography'],
    tips: 'Carry good walking shoes.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1200/day', medium: '₹3500/day', high: '₹8000/day' },
    itinerary: ['Day 1: Virupaksha & local ruins', 'Day 2: Vittala Temple & Stone chariot', 'Day 3: Hampi Bazaar & river coracle']
  },
  {
    _id: '68c272fa030b9fcba7e715ad',
    title: 'Shimla',
    description: 'Famous hill station with colonial charm.',
    imgSrc: '/images/shimla.jpg',
    location: 'Himachal Pradesh',
    bestTimeToVisit: 'March to June',
    activities: ['Mall Road Walk', 'Toy Train Ride', 'Hiking'],
    tips: 'Book hotels early in summer.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1800/day', medium: '₹4500/day', high: '₹10000/day' },
    itinerary: ['Day 1: Mall Road & Ridge', 'Day 2: Kufri & local adventure', 'Day 3: Jakhu Temple & walk']
  },
    {
    _id: '68c2a04b030b9fcba7e715af',
    title: 'Leh-Ladakh',
    description: 'Adventure paradise with mountains, lakes, and unique culture.',
    imgSrc: '/images/leh.jpg',
    location: 'Ladakh',
    bestTimeToVisit: 'June to September',
    activities: ['Trekking', 'Biking', 'Photography'],
    tips: 'Acclimatize properly to high altitude.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2500/day', medium: '₹6000/day', high: '₹12000/day' },
    itinerary: ['Day 1: Leh local sightseeing', 'Day 2: Pangong Lake', 'Day 3: Nubra Valley']
  },
  {
    _id: '68c2a063030b9fcba7e715b1',
    title: 'Kerala',
    description: 'God’s Own Country, with backwaters, beaches, and lush greenery.',
    imgSrc: '/images/kerala.jpg',
    location: 'Kerala',
    bestTimeToVisit: 'October to March',
    activities: ['Backwater Cruise', 'Ayurvedic Spa', 'Hill Station Visit'],
    tips: 'Try local cuisine like Kerala Sadya.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹5000/day', high: '₹10000/day' },
    itinerary: ['Day 1: Alleppey backwaters', 'Day 2: Munnar hills', 'Day 3: Kochi sightseeing']
  },
  {
    _id: '68c2a0a0030b9fcba7e715b3',
    title: 'Shillong',
    description: 'City of waterfalls and greenery in Northeast India.',
    imgSrc: '/images/shillong.jpg',
    location: 'Meghalaya',
    bestTimeToVisit: 'October to June',
    activities: ['Waterfalls', 'Local Markets', 'Hiking'],
    tips: 'Carry rain gear; it rains often.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: Elephant Falls & Shillong Peak', 'Day 2: Mawlynnong village', 'Day 3: Local markets & cafes']
  },
  {
    _id: '68c2a0c6030b9fcba7e715b7',
    title: 'Pondicherry',
    description: 'Charming coastal town with French colonial architecture, beaches, and cafes.',
    imgSrc: '/images/pondicherry.jpg',
    location: 'Puducherry',
    bestTimeToVisit: 'October to March',
    activities: ['Beach Walks', 'Cafe Hopping', 'Explore Auroville'],
    tips: 'Rent a bicycle or scooter to explore the town easily.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: Promenade & French Quarter', 'Day 2: Auroville & beaches', 'Day 3: Local cafes & culture']
  },
  {
    _id: '68c2a0d7030b9fcba7e715b9',
    title: 'Coorg',
    description: 'Known as the Scotland of India, famous for coffee plantations and hills.',
    imgSrc: '/images/coorg.jpg',
    location: 'Karnataka',
    bestTimeToVisit: 'October to March',
    activities: ['Trekking', 'Coffee Plantation Tour', 'Waterfalls'],
    tips: 'Stay in homestays for authentic experience.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹5000/day', high: '₹10000/day' },
    itinerary: ['Day 1: Abbey & Iruppu waterfalls', 'Day 2: Coffee plantation tour', 'Day 3: Local trekking & relaxation']
  },
  {
    _id: '68c2a152030b9fcba7e715bb',
    title: 'Agra',
    description: 'Home of the iconic Taj Mahal and rich Mughal history.',
    imgSrc: '/images/agra.jpg',
    location: 'Uttar Pradesh',
    bestTimeToVisit: 'October to March',
    activities: ['Taj Mahal Tour', 'Fort Visit', 'Local Food'],
    tips: 'Visit early morning to avoid crowds.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1200/day', medium: '₹3500/day', high: '₹8000/day' },
    itinerary: ['Day 1: Taj Mahal sunrise', 'Day 2: Agra Fort & local bazaar', 'Day 3: Fatehpur Sikri day trip']
  },
  {
    _id: '68c2a189030b9fcba7e715bd',
    title: 'Cherrapunji',
    description: 'Known for living root bridges, waterfalls, and extreme rainfall.',
    imgSrc: '/images/cherrapunji.jpg',
    location: 'Meghalaya',
    bestTimeToVisit: 'October to May',
    activities: ['Living Root Bridge Trek', 'Waterfall Visits', 'Cave Exploration'],
    tips: 'Carry rain gear as rainfall is frequent.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: Nohkalikai Falls & trek', 'Day 2: Living Root Bridge', 'Day 3: Mawsmai Caves & local village']
  },
  {
    _id: '68c2a1ce030b9fcba7e715bf',
    title: 'Daman & Diu',
    description: 'Serene coastal destination with Portuguese heritage, beaches, and forts.',
    imgSrc: '/images/daman.jpg',
    location: 'Daman and Diu',
    bestTimeToVisit: 'October to March',
    activities: ['Beach Walks', 'Fort Exploration', 'Water Sports'],
    tips: 'Try the local seafood and explore both Daman and Diu sides.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: Daman beaches & forts', 'Day 2: Diu sightseeing', 'Day 3: Relax & water sports']
  },
  {
    _id: '68c2a1e3030b9fcba7e715c1',
    title: 'Ziro Valley',
    description: 'Picturesque valley in Arunachal Pradesh, known for rice fields, pine hills, and tribal culture.',
    imgSrc: '/images/ziro.jpg',
    location: 'Arunachal Pradesh',
    bestTimeToVisit: 'March to October',
    activities: ['Trekking', 'Tribal Culture Experience', 'Ziro Music Festival'],
    tips: 'Plan visit during the Ziro Music Festival for unique experience.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹4500/day', high: '₹10000/day' },
    itinerary: ['Day 1: Ziro town & tribal villages', 'Day 2: Music festival & trekking', 'Day 3: Explore rice fields & local markets']
  },
  {
    _id: '68c2a210030b9fcba7e715c3',
    title: 'Spiti Valley',
    description: 'Cold desert mountain valley, monasteries, rugged landscapes, and adventure trekking.',
    imgSrc: '/images/spiti.jpg',
    location: 'Himachal Pradesh',
    bestTimeToVisit: 'May to October',
    activities: ['Monastery Visits', 'Trekking', 'Camping', 'Photography'],
    tips: 'Carry warm clothes; roads can be tough.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹2000/day', medium: '₹5000/day', high: '₹12000/day' },
    itinerary: ['Day 1: Kaza town & Key Monastery', 'Day 2: Tabo Monastery & trekking', 'Day 3: Chandratal Lake camping']
  },
  {
    _id: '68c2a2c4030b9fcba7e715c5',
    title: 'Landour',
    description: 'Quiet hill station near Mussoorie with colonial charm and scenic views.',
    imgSrc: '/images/landour.jpg',
    location: 'Uttarakhand',
    bestTimeToVisit: 'March to June and September to November',
    activities: ['Nature Walks', 'Café Hopping', 'Sightseeing'],
    tips: 'Carry comfortable walking shoes and light woolens.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹3500/day', high: '₹8000/day' },
    itinerary: ['Day 1: Landour walks & Café hopping', 'Day 2: Mussoorie hill sightseeing', 'Day 3: Local nature trails']
  },
  {
    _id: '68c2a2f4030b9fcba7e715c7',
    title: 'Mussoorie',
    description: 'The Queen of Hills, with waterfalls, viewpoints, and colonial-era charm.',
    imgSrc: '/images/mussoorie.jpg',
    location: 'Uttarakhand',
    bestTimeToVisit: 'March to June and September to November',
    activities: ['Cable Car Ride', 'Kempty Falls Visit', 'Mall Road Stroll'],
    tips: 'Avoid peak tourist season for a peaceful trip.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1800/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: Mall Road & viewpoints', 'Day 2: Kempty Falls & cable car', 'Day 3: Trekking & relax']
  },
  {
    _id: '68c2a340030b9fcba7e715c9',
    title: 'Chopta',
    description: 'Serene hill station in Uttarakhand, also called "Mini Switzerland of India".',
    imgSrc: '/images/chopta.jpg',
    location: 'Uttarakhand',
    bestTimeToVisit: 'March to May and September to November',
    activities: ['Tungnath Trek', 'Camping', 'Bird Watching'],
    tips: 'Carry warm clothes as temperatures can drop suddenly.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹3500/day', high: '₹8000/day' },
    itinerary: ['Day 1: Tungnath trek', 'Day 2: Camping & bird watching', 'Day 3: Chopta local exploration']
  },
  {
    _id: '68c2a355030b9fcba7e715cb',
    title: 'Nainital',
    description: 'Picturesque hill station with lakes and pleasant weather.',
    imgSrc: '/images/nainital.jpg',
    location: 'Uttarakhand',
    bestTimeToVisit: 'March to June and September to November',
    activities: ['Boating in Naini Lake', 'Cable Car Ride', 'Shopping at Mall Road'],
    tips: 'Book accommodations early during peak seasons.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1800/day', medium: '₹4000/day', high: '₹9000/day' },
    itinerary: ['Day 1: Naini Lake boating', 'Day 2: Snow View & cable car', 'Day 3: Local shopping & trek']
  },
  {
    _id: '68c2a36c030b9fcba7e715cd',
    title: 'Ranikhet',
    description: 'Peaceful hill station known for scenic beauty, orchards, and Himalayan views.',
    imgSrc: '/images/ranikhet.jpg',
    location: 'Uttarakhand',
    bestTimeToVisit: 'March to June and September to November',
    activities: ['Nature Walks', 'Golfing', 'Visit to Jhula Devi Temple'],
    tips: 'Ideal for travelers seeking peace and less-crowded hill stations.',
    mapLink: 'https://goo.gl/maps/...',
    budgetPlan: { low: '₹1500/day', medium: '₹3500/day', high: '₹8000/day' },
    itinerary: ['Day 1: Ranikhet walk & nature', 'Day 2: Golfing & local temple', 'Day 3: Scenic photography & relax']
  }
];

export default destinationsData;


